all:
  vars:
    ansible_connection: local
    app_root: /opt/full-lifecycle-demo
    app_user: deployer
    docker_compose_project: full_lifecycle
  children:
    staging:
      hosts:
        staging-web-1:
        staging-db-1:
        staging-cache-1:
    production:
      hosts:
        prod-web-1:
        prod-web-2:
        prod-db-1:
        prod-cache-1:
    webservers:
      hosts:
        staging-web-1:
        prod-web-1:
        prod-web-2:
    databases:
      hosts:
        staging-db-1:
        prod-db-1:
    caches:
      hosts:
        staging-cache-1:
        prod-cache-1:
