[webservers]
web1 ansible_connection=local ansible_host=127.0.0.1 nginx_server_name=web1.infra.lab nginx_port=8081
web2 ansible_connection=local ansible_host=127.0.0.1 nginx_server_name=web2.infra.lab nginx_port=8082

[db_master]
db-master ansible_connection=local ansible_host=127.0.0.1 postgresql_role=master postgresql_port=5432

[db_replica]
db-replica ansible_connection=local ansible_host=127.0.0.1 postgresql_role=replica postgresql_port=5433

[loadbalancers]
lb1 ansible_connection=local ansible_host=127.0.0.1 haproxy_frontend_port=8080

[monitoring]
mon1 ansible_connection=local ansible_host=127.0.0.1 prometheus_port=9090 grafana_port=3000

[database:children]
db_master
db_replica

[all:vars]
ansible_python_interpreter=/usr/bin/python3
